### ISSUE TITLE
Hyperparameters for reproducing Schema2QA results

### ISSUE THREAD

**Issue by harm-devries** [stanford-oval/genienlp#116]
Hi again!

I'm trying to reproduce the results of the Schema2QA paper. The docs mention that in order to reproduce the paper results I should run with `<=0.5`. However, the recommended BERT-LSTM model seem to have different hyperparameters for this version:
```
genienlp train --tasks almond --train_iterations 50000 --data <datadir> --save <model_dir> \
  --model TransformerLSTM --pretrained_model bert-base-cased --trainable_decoder_embedding 50
```

What hyperparameters should I use for the `0.5` version? I believe the following flags are relevant: --model, --encoder, --decoder, --encoder_embeddings, --train_encoder_embeddings, --context_embeddings, --train_context_embeddings, --question_embeddings, --train_question_embeddings. Thanks!

**Comment by sileix** [comment]
Hi there, 

Here is the exact hyperparameter we used for the BERT-LSTM model: 
```
--train_iterations 60000 --dimension 768 --transformer_hidden 768 --trainable_decoder_embeddings 50 --encoder_embeddings=bert-base-uncased --decoder_embeddings= --seq2seq_encoder=Identity --rnn_layers 1 --transformer_heads 12 --transformer_layers 0 --rnn_zero_state=average --train_encoder_embeddings --transformer_lr_multiply 0.1
```

Which docs are you referring to? Sorry about the confusion, I will update to docs.

**Comment by harm-devries** [comment]
Ok thanks! Which commit do you recommend? 

I was looking at the readme, specifically the small note at the end of the `train a semantic parser` section.

**Comment by sileix** [comment]
> Ok thanks! Which commit do you recommend?
> 
> I was looking at the readme, specifically the small note at the end of the `train a semantic parser` section.

I see. For AutoQA, you should use tag `emnlp2020-autoqa-camera-ready`: https://github.com/stanford-oval/genienlp/tree/emnlp2020-autoqa-camera-ready

**Comment by harm-devries** [comment]
> For AutoQA, you should use tag emnlp2020-autoqa-camera-ready

And for schema2qa?

**Comment by sileix** [comment]
> > For AutoQA, you should use tag emnlp2020-autoqa-camera-ready
> 
> And for schema2qa?

We do have a tag `cikm2020-camera-ready` for it, but they should produce the same result.
