### ISSUE TITLE
Question about synthesis data in the train.csv

### ISSUE THREAD

**Issue by kaoshizhou** [stanford-oval/genienlp#131]
Hi @s-jse @gcampax ,

I am very interested in your AutoQA paper, but I encounter a question when reading the synthesized training dataset.

Here is an example in the basketball domain:

ARS4-87    
players whose blocks ( in a season ) exceeds 3    
==================================
(call edu.stanford.nlp.sempre.overnight.SimpleWorld.listValue (call edu.stanford.nlp.sempre.overnight.SimpleWorld.getProperty ((lambda s (call edu.stanford.nlp.sempre.overnight.SimpleWorld.filter (var s) (call edu.stanford.nlp.sempre.overnight.SimpleWorld.ensureNumericProperty (string num_blocks)) (string <=) (call edu.stanford.nlp.sempre.overnight.SimpleWorld.ensureNumericEntity (number 3 block)))) (call edu.stanford.nlp.sempre.overnight.SimpleWorld.domain (string player))) (string player)))

In my understanding, "exceeds 3"means ">=3", while the ground truth logic form uses "<="

I'd appreciate that if you can help me understand this example.

**Comment by s-jse** [comment]
Examples with `A` in their id are **A**utoparaphrased, so this example is the result of an error that the neural paraphrasing model has introduced, as described in section 5.1 of the paper. Here, "no more than" is paraphrased to "exceeds". In the same file, for example `ARS4-121` is a correct paraphrase of the original sentence.
