### ISSUE TITLE
Can't load weights for 'sshleifer/bart-tiny-random'

### ISSUE THREAD

**Issue by hzg456** [stanford-oval/genienlp#161]
error showed in terminal：
```
OSError: Can't load weights for 'sshleifer/bart-tiny-random'. Make sure that:

- 'sshleifer/bart-tiny-random' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'sshleifer/bart-tiny-random' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.
```

It seems that 'sshleifer/bart-tiny-random' is not listed on 'https://huggingface.co/models'
Could you please tell me how to solve this problem？
thx！

**Comment by gcampax** [comment]
It is listed at https://huggingface.co/sshleifer/bart-tiny-random

Please check your network connection and file system permissions in the transformers cache directory (~/.cache/huggingface on linux)

**Comment by hzg456** [comment]
thank you for your helping！
