### ISSUE TITLE
Bootleg type mapping should be configurable

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genienlp#175]
Currently, the mapping between Almond types and Bootleg QIDs is defined in a fixed JSON file (es_material/almond_type2qid.json) which also depends on the domain.

Instead, the path to this file should be configurable so this file can be dynamically generated during synthesis based on the information in Thingpedia manifests.

Filing this issue for tracking so we don't forget.

**Comment by gcampax** [comment]
After discussion on Slack, we agreed the NED code needs some refactoring:

We agreed to:
1. [x] we rename "Feature" to "Entity"
2. [x] we stop using the word QID everywhere, and either say "type_id" or "entity_id" so we don't get confused everywhere
3. [x] we make type_id to be the (numeric) QID of the type given by bootleg - or a "normalized" type QID given by the almond_type_* files, which we simplify to be "exact" and "substring" in one file, or maybe some glob-like thing and a simple mapping
4. [x] we remove "ned_features", "ned_features_default", and "ned_feature_size", and replace it with "max_entity_per_span" or similar which is just a number, tells you how many things to put with |
5. [x] we make a "add_entity_to_text" = (type, qid) to decide what to append to the entity
6. [x] we put the wikidata type name of the (normalized) type id in the input

**Comment by Mehrad0711** [comment]
Addressed in #183
