### ISSUE TITLE
Should not depend on seaborn or matplotlib

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genienlp#35]
Plotting libraries are big and bring down a ton of indirect dependencies - font packages, image processing code, etc.
We obviously don't need those libraries at runtime so we should not depend on them. 
Stuff that is obviously for human consumption must not be part of the core library.

Tagging @s-jse who added them.

**Comment by s-jse** [comment]
I'll remove matplotlib. I think @Mehrad0711 's translation code uses seaborn.
