### ISSUE TITLE
Multi-GPU support for training and inference

### ISSUE THREAD

**Issue by s-jse** [stanford-oval/genienlp#50]
- Currently, the code does not support distributed training on multiple GPUs.
- Inference is done on multiple GPUs by splitting the input data files on disk, running completely independent Python processes, and combining the result files at the end. This avoids the overheads of  Pytorch's `DataParallel`, but it would be much cleaner and potentially as fast if we use `DistributedDataParallel ` instead.

**Comment by gcampax** [comment]
Wait I thought we support multi GPU training already, through DataParallel. And DataParallel is supposed to be faster and more recommended compared to DistributedDataParallel, according to the Torch documentation.

**Comment by gcampax** [comment]
Oh it looks like they reversed their recommendation, and now they recommend DistributedDataParallel.

**Comment by s-jse** [comment]
> 
> 
> Wait I thought we support multi GPU training already, through DataParallel. And DataParallel is supposed to be faster and more recommended compared to DistributedDataParallel, according to the Torch documentation.

Have you tested the multi-GPU training code?

**Comment by gcampax** [comment]
I think @Mehrad0711  uses it. I haven't tested it.

**Comment by Mehrad0711** [comment]
Yeah, multi-gpu training works (via DataParallel). We can test with the Distributed version and see the speed difference.
