### ISSUE TITLE
MT5 is too big to be tested on Travis

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genienlp#63]
The smallest mT5 model has 300M parameters, and that dies in Travis with:
```
RuntimeError: [enforce fail at CPUAllocator.cpp:65] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 568227200 bytes. Error code 12 (Cannot allocate memory)
```
(ref: https://travis-ci.com/github/stanford-oval/genienlp)

Not sure what to do here.

**Comment by Mehrad0711** [comment]
You can drop it from the tests for now. Until someone adds "mt5-tiny".

**Comment by Mehrad0711** [comment]
Is it not possible to increase Travis memory? 
Because if we want to address #51, we need to test with actual Bart and T5 models (not randomized versions) to check the outputs and I think bart-base was failing too.

**Comment by gcampax** [comment]
Travis has 7.5G of RAM, and it's not possible to increase it, no. I'm actually surprised that's not enough to run by the way.

**Comment by s-jse** [comment]
Have you tried reducing the batch size in tests? The default batch size is suitable for 16GB GPUs.

**Comment by gcampax** [comment]
Reducing the batch size worked to get the tests through.
