### ISSUE TITLE
Update to Transformers 4.2

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/genienlp#75]
We're currently pinned to 4.1 so it's not a huge issue, but flagging it here for later.
Transformers 4.2 breaks us because of https://github.com/huggingface/transformers/pull/9150.
The generation code calls the models with new "output_attentions" and "output_hidden_states" kwargs. Not sure what we should do here, cause we don't care about those? Except sometimes we do, like for translation?

**Comment by Mehrad0711** [comment]
Addressed in #105
