### ISSUE TITLE
When using predict.py for multi-GPU prediction, will the model be loaded multiple times?

### ISSUE THREAD

**Issue by xiaomore** [stanford-oval/genienlp#77]
Excuse me, I have a question about using predict.py to predict on multi-GPU with multiprocessing. My model file will load multi times. The number of model loads is the same as the number of processes (or the number of cuda), which will take more time. How can I solve it? Thanks!

**Comment by s-jse** [comment]
Hi @xiaomore!

In a multi-GPU setting, `predict.py` runs n _completely independent_ processes to avoid using Pytorch's `DataParallel` and incurring its overheads. Therefore, it loads the model n times and puts one model on each GPU device. All operations are done in separate processes, and the only non-parallelized part (i.e. reading from disk) is fast for typical models and datasets, and a very small part of the prediction wall time.

If you see specific speed issues, please provide more information and we would be happy to help.

**Comment by xiaomore** [comment]
> Hi @xiaomore!
> 
> In a multi-GPU setting, `predict.py` runs n _completely independent_ processes to avoid using Pytorch's `DataParallel` and incurring its overheads. Therefore, it loads the model n times and puts one model on each GPU device. All operations are done in separate processes, and the only non-parallelized part (i.e. reading from disk) is fast for typical models and datasets, and a very small part of the prediction wall time.
> 
> If you see specific speed issues, please provide more information and we would be happy to help.

**I'm very thanks for your reply. Part of my code is as follows, please help me think about how to initialize it once. Thanks!**

```
class TextRecognizer:
    def __init__(self, rec_model_param, txt_det_model_conf, txt_det_model_param, tab_det_model_conf,
                 tab_det_model_param, proj_dir, font_path, visual_flag, gpu_device):
        self.initModel(rec_model_param, txt_det_model_conf, txt_det_model_param, tab_det_model_conf,
                       tab_det_model_param, proj_dir, gpu_device)

    def initModel(self, rec_model_param, txt_det_model_conf, txt_det_model_param, tab_det_model_conf,
                  tab_det_model_param, proj_dir, gpu_device):
        sys.path.append(proj_dir)
        # Initialize the weight file here, but if there are three GPUs (devices), it will be initialized 
        # three times, which will take three times the time.
        global_conf.init_environ_api(gpu_device, proj_dir, rec_model_param, txt_det_model_conf, txt_det_model_param,
                                     tab_det_model_conf, tab_det_model_param)
       ......

def run(arg, device):
    textRecognizer = TextRecognizer(
        rec_model_param=args.recModelParam,
        txt_det_model_conf=args.txtDetModelConfig,
        txt_det_model_param=args.txtDetModelParam,
        tab_det_model_conf=args.tabDetModelConfig,
        tab_det_model_param=args.tabDetModelParam,
        proj_dir=args.proDir,
        font_path=args.fontPath,
        visual_flag=args.useVisual,
        gpu_device=device
    )
    textRecognizer.fileTxtExtract(arg.input, arg.outputDir)

if __name__ == '__main__':
    set_seed(args)
    mp.set_start_method('spawn')

    devices = init_devices(args)
    if args.device is not None:
        devices = [devices[i] for i in args.device]

    if len(devices) > 1:
        # Independent multi-GPU generation
        all_processes = []
        all_data_folders = split_folder_on_disk(args.filePath, len(devices))
        for device_id in range(len(devices)):
            copy_args = copy.copy(args)
            copy_args.filePath = all_data_folders[device_id]

            p = Process(target=run, args=(copy_args, devices[device_id]))
            p.start()
            all_processes.append(p)
        for p in all_processes:
            p.join()

        # for folder in all_data_folders:
        #     shutil.rmtree(folder)
    else:
        run(args, devices[0])
```

**Comment by gcampax** [comment]
Hi @xiaomore ! Is your question specifically about genienlp, or about a different project? In the latter case, you might find that you'll receive better answers in a more general forum like StackOverflow.
This said, generally speaking, the cost of initializing a model should be negligible compared to the cost of running the model on the validation or test set. The only expensive part of initialization is loading the model file from disk, and in practice, one process does the actual IO, while the other processes read from kernel cache. It's all very cheap.
(There are other aspects of initialization that are expensive, such as tokenizing the test set or uploading the model to GPU, but those need to be done separately by each process, which operates on a different GPU and a different slice of the test set).
